// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CompiledModels
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var device = DeviceEntityType.Create(this);
            var user = UserEntityType.Create(this);

            DeviceEntityType.CreateForeignKey1(device, user);

            DeviceEntityType.CreateAnnotations(device);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "8.0.16");
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var device = FindEntityType("Device")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            device.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var deviceTableBase = new TableBase("Device", null, relationalModel);
            var createdUtcColumnBase = new ColumnBase<ColumnMappingBase>("CreatedUtc", "TEXT", deviceTableBase);
            deviceTableBase.Columns.Add("CreatedUtc", createdUtcColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", deviceTableBase);
            deviceTableBase.Columns.Add("Id", idColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", deviceTableBase);
            deviceTableBase.Columns.Add("Name", nameColumnBase);
            var serialNumberColumnBase = new ColumnBase<ColumnMappingBase>("SerialNumber", "TEXT", deviceTableBase)
            {
                IsNullable = true
            };
            deviceTableBase.Columns.Add("SerialNumber", serialNumberColumnBase);
            var userIdColumnBase = new ColumnBase<ColumnMappingBase>("UserId", "INTEGER", deviceTableBase);
            deviceTableBase.Columns.Add("UserId", userIdColumnBase);
            relationalModel.DefaultTables.Add("Device", deviceTableBase);
            var deviceMappingBase = new TableMappingBase<ColumnMappingBase>(device, deviceTableBase, true);
            deviceTableBase.AddTypeMapping(deviceMappingBase, false);
            defaultTableMappings.Add(deviceMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, device.FindProperty("Id")!, deviceMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdUtcColumnBase, device.FindProperty("CreatedUtc")!, deviceMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, device.FindProperty("Name")!, deviceMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)serialNumberColumnBase, device.FindProperty("SerialNumber")!, deviceMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase, device.FindProperty("UserId")!, deviceMappingBase);

            var tableMappings = new List<TableMapping>();
            device.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var devicesTable = new Table("Devices", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", devicesTable);
            devicesTable.Columns.Add("Id", idColumn);
            var createdUtcColumn = new Column("CreatedUtc", "TEXT", devicesTable);
            devicesTable.Columns.Add("CreatedUtc", createdUtcColumn);
            var nameColumn = new Column("Name", "TEXT", devicesTable);
            devicesTable.Columns.Add("Name", nameColumn);
            var serialNumberColumn = new Column("SerialNumber", "TEXT", devicesTable)
            {
                IsNullable = true
            };
            devicesTable.Columns.Add("SerialNumber", serialNumberColumn);
            var userIdColumn = new Column("UserId", "INTEGER", devicesTable);
            devicesTable.Columns.Add("UserId", userIdColumn);
            var pK_Devices = new UniqueConstraint("PK_Devices", devicesTable, new[] { idColumn });
            devicesTable.PrimaryKey = pK_Devices;
            var pK_DevicesUc = RelationalModel.GetKey(this,
                "Device",
                new[] { "Id" });
            pK_Devices.MappedKeys.Add(pK_DevicesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_DevicesUc).Add(pK_Devices);
            devicesTable.UniqueConstraints.Add("PK_Devices", pK_Devices);
            var iX_Devices_UserId = new TableIndex(
            "IX_Devices_UserId", devicesTable, new[] { userIdColumn }, false);
            var iX_Devices_UserIdIx = RelationalModel.GetIndex(this,
                "Device",
                new[] { "UserId" });
            iX_Devices_UserId.MappedIndexes.Add(iX_Devices_UserIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Devices_UserIdIx).Add(iX_Devices_UserId);
            devicesTable.Indexes.Add("IX_Devices_UserId", iX_Devices_UserId);
            relationalModel.Tables.Add(("Devices", null), devicesTable);
            var devicesTableMapping = new TableMapping(device, devicesTable, true);
            devicesTable.AddTypeMapping(devicesTableMapping, false);
            tableMappings.Add(devicesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, device.FindProperty("Id")!, devicesTableMapping);
            RelationalModel.CreateColumnMapping(createdUtcColumn, device.FindProperty("CreatedUtc")!, devicesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, device.FindProperty("Name")!, devicesTableMapping);
            RelationalModel.CreateColumnMapping(serialNumberColumn, device.FindProperty("SerialNumber")!, devicesTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn, device.FindProperty("UserId")!, devicesTableMapping);

            var user = FindEntityType("User")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            user.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var userTableBase = new TableBase("User", null, relationalModel);
            var createdUtcColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedUtc", "TEXT", userTableBase);
            userTableBase.Columns.Add("CreatedUtc", createdUtcColumnBase0);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("Email", "TEXT", userTableBase)
            {
                IsNullable = true
            };
            userTableBase.Columns.Add("Email", emailColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", userTableBase);
            userTableBase.Columns.Add("Id", idColumnBase0);
            var usernameColumnBase = new ColumnBase<ColumnMappingBase>("Username", "TEXT", userTableBase);
            userTableBase.Columns.Add("Username", usernameColumnBase);
            relationalModel.DefaultTables.Add("User", userTableBase);
            var userMappingBase = new TableMappingBase<ColumnMappingBase>(user, userTableBase, true);
            userTableBase.AddTypeMapping(userMappingBase, false);
            defaultTableMappings0.Add(userMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, user.FindProperty("Id")!, userMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdUtcColumnBase0, user.FindProperty("CreatedUtc")!, userMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, user.FindProperty("Email")!, userMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)usernameColumnBase, user.FindProperty("Username")!, userMappingBase);

            var tableMappings0 = new List<TableMapping>();
            user.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var usersTable = new Table("Users", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", usersTable);
            usersTable.Columns.Add("Id", idColumn0);
            var createdUtcColumn0 = new Column("CreatedUtc", "TEXT", usersTable);
            usersTable.Columns.Add("CreatedUtc", createdUtcColumn0);
            var emailColumn = new Column("Email", "TEXT", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("Email", emailColumn);
            var usernameColumn = new Column("Username", "TEXT", usersTable);
            usersTable.Columns.Add("Username", usernameColumn);
            var pK_Users = new UniqueConstraint("PK_Users", usersTable, new[] { idColumn0 });
            usersTable.PrimaryKey = pK_Users;
            var pK_UsersUc = RelationalModel.GetKey(this,
                "User",
                new[] { "Id" });
            pK_Users.MappedKeys.Add(pK_UsersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UsersUc).Add(pK_Users);
            usersTable.UniqueConstraints.Add("PK_Users", pK_Users);
            relationalModel.Tables.Add(("Users", null), usersTable);
            var usersTableMapping = new TableMapping(user, usersTable, true);
            usersTable.AddTypeMapping(usersTableMapping, false);
            tableMappings0.Add(usersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, user.FindProperty("Id")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(createdUtcColumn0, user.FindProperty("CreatedUtc")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn, user.FindProperty("Email")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(usernameColumn, user.FindProperty("Username")!, usersTableMapping);
            var fK_Devices_Users_UserId = new ForeignKeyConstraint(
                "FK_Devices_Users_UserId", devicesTable, usersTable,
                new[] { userIdColumn },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Cascade);
            var fK_Devices_Users_UserIdFk = RelationalModel.GetForeignKey(this,
                "Device",
                new[] { "UserId" },
                "User",
                new[] { "Id" });
            fK_Devices_Users_UserId.MappedForeignKeys.Add(fK_Devices_Users_UserIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Devices_Users_UserIdFk).Add(fK_Devices_Users_UserId);
            devicesTable.ForeignKeyConstraints.Add(fK_Devices_Users_UserId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_Devices_Users_UserId);
            return relationalModel.MakeReadOnly();
        }
    }
}
